name: JenkinsPythonSDK

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Print directory structure
        run: |
          ls -R
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run specific test file
        run: |
          python -m pytest tests/jenkins.py
      
  test-python36:
      name: Test on Ubuntu 20.04 with Python 3.6
      runs-on: ubuntu-20.04
      continue-on-error: true
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Print directory structure
          run: |
            ls -R
            
        - name: Set up Python 3.6
          uses: actions/setup-python@v5
          with:
            python-version: 3.6
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest
  
        - name: Run specific test file
          run: |
            python -m pytest tests/jenkins.py
