name: JenkinsPythonSDK

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          architecture: x64

      - name: Print directory structure
        run: |
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run specific test file
        run: |
          python -m pytest tests/jenkins.py
